version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - AWS_REGION=sa-east-1
      - DYNAMODB_TABLE_NAME=ia-threat-modeling-history-dev
      - S3_BUCKET_NAME=ia-threat-modeling-uploads-dev-75ee5470
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config
    user: root
    volumes:
      - ~/.aws:/root/.aws
